# Generated by Django 5.2.10 on 2026-01-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categery_images/%Y/%m/%d/'),
        ),
    ]
